[build]
builder = "nixpacks"

[deploy]
startCommand = "export DJANGO_SETTINGS_MODULE=flipiq_backend.settings_production && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn flipiq_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
healthcheckPath = "/health/"
healthcheckTimeout = 300

[variables]
PORT = "8080"
